services:
  - type: web
    name: fish-disease-app
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    runtime: python-3.11.9