services:
  - type: web
    name: fish-disease-app
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt && python scripts/download_models_hf.py
    startCommand: gunicorn app:app
    plan: free
    runtime: python-3.11.9